### ISSUE TITLE
Is there an easy way to default date transforms to DateTimeUtc?

### ISSUE THREAD

**Issue by edjo23** [Avanade/Beef#49]
Hi, we would like to enforce all of our date times to be UTC regardless of local time zone. I see we can do this by setting the DateTimeTransform on all dates but was wondering if there was a easy way to make DateTimeUtc the default.

If not can I request this as a feature enhancement, thanks.

**Comment by chullybun** [comment]
Hi there. Unfortunately, no there is not a simple way to change this behaviour. And, yes you may request this as a feature enhancement 🤪 I think that this should be relatively straight forward(-ish) change - I will look into it 👍

**Comment by edjo23** [comment]
Awesome, thanks. Much appreciated 😄

**Comment by chullybun** [comment]
OK. Took a little longer than expected, but I think I have got there. 

The `Beef.Entities.Cleaner` class has a `DefaultDateTimeTransform` that can now be set (overridden); I have defaulted this to `DateTimeUtc` (the previous version was `DateTimeLocal`) - so this is a change in behaviour. The code-gen has been updated so that the default options for `StringTrim`, `StringTransform` and `DateTimeTransform` will be `UseDefault`. They can still be overridden where required; e.g. `DateOnly`. Internally, anywhere that a `DateTime.Now` was being performed, it is wrapped as `Cleaner.Clean(DateTime.Now)` to ensure the right `DateTimeKind` is applied. 

Note that the ADO.NET framework always returns a `DateTime` with `DateTimeKind.Unspecified` - it's `Kind` is set accordingly, but no adjustment to the time zone is made as it is assumed it was persisted as the defined `DateTimeKind` (e.g. UTC or local). Both the SQL `DATETIME` and `DATETIME2` do not store offset, you would need to use `DATETIMEOFFSET` if required. 

I'll publish the updated NuGet packages in the next hour or two. Let me know how you get on. You might owe me a Jee's Burger for this one 😜

**Comment by edjo23** [comment]
Thanks for that. Yeah that was more than I was expecting 😄. I'll get this in as soon as possible and let you know how we go.

Yes Jee's Burgers on me, I do hope they are still around, it's been a couple months since I've been into the city!
